Compose some more, refactor input passing

diff --git a/stop/action.yml b/stop/action.yml
--- a/stop/action.yml
+++ b/stop/action.yml
@@ -6,6 +6,15 @@ inputs:
   aws-region:
     description: AWS region
     required: true
+  aws-access-key-id:
+    description: AWS access key ID
+    required: true
+  aws-secret-access-key:
+    description: AWS secret access key
+    required: true
+  aws-role-to-assume:
+    description: AWS IAM role to assume
+    required: false
   github-token:
     description: GitHub auth token (PAT with repo scope)
     required: true
@@ -22,21 +31,33 @@ inputs:
 runs:
   using: composite
   steps:
-    - shell: bash
+
+    - id: auth
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-region: ${{ inputs.aws-region }}
+        aws-access-key-id: ${{ inputs.aws-access-key-id }}
+        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
+        role-to-assume: ${{ inputs.aws-role-to-assume }}
+        role-session-name: ec2-actions-runner-stop
+        role-duration-seconds: 900
+
+    - id: main
+      shell: bash
       run: |
-        runner_id='${{ inputs.runner-id }}'
-        instance_id='${{ inputs.instance-id }}'
-      
-        echo "Deregistering repository runner: $runner_id ..."
+        echo "Deregistering repository runner: $RUNNER_ID ..."
         
-        gh api -X DELETE -H "Accept: application/vnd.github.v3+json" \
-          repos/${{ inputs.github-repo }}/actions/runners/$runner_id || echo "WARN: Failed to deregister runner"
+        gh api -X DELETE -H 'Accept: application/vnd.github.v3+json' \
+          "repos/$GITHUB_REPO/actions/runners/$RUNNER_ID" || echo "WARN: Failed to deregister runner"
         
-        echo "Terminating EC2 instance: $instance_id ..."
+        echo "Terminating EC2 instance: $INSTANCE_ID ..."
         
-        aws ec2 terminate-instances --instance-ids "$instance_id" > /dev/null
+        aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" > /dev/null
         
         echo "Repository runner stopped"
       env:
         GH_TOKEN: ${{ inputs.github-token }}
         AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
+        RUNNER_ID: ${{ inputs.runner-id }}
+        GITHUB_REPO: ${{ inputs.github-repo }}
+        INSTANCE_ID: ${{ inputs.instance-id }}
