Update action.yml

diff --git a/stop/action.yml b/stop/action.yml
--- a/stop/action.yml
+++ b/stop/action.yml
@@ -26,13 +26,14 @@ runs:
       
         echo "Deregistering repository runner: $runner_id ..."
         
-        gh api -X DELETE -H "Accept: application/vnd.github.v3+json" repos/${{ github.repository }}/actions/runners/$runner_id || echo "Failed to deregister runner"
+        gh api -X DELETE -H "Accept: application/vnd.github.v3+json" \
+          repos/${{ github.repository }}/actions/runners/$runner_id || echo "WARN: Failed to deregister runner"
         
         echo "Terminating EC2 instance: $instance_id ..."
         
         aws ec2 terminate-instances --instance-ids "$instance_id" > /dev/null
         
-        echo "Runner successfully stopped"
+        echo "Repository runner stopped"
       env:
         GH_TOKEN: ${{ inputs.github-token }}
         AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
