Update action.yml

diff --git a/stop/action.yml b/stop/action.yml
--- a/stop/action.yml
+++ b/stop/action.yml
@@ -46,16 +46,23 @@ runs:
     - id: main
       shell: bash
       run: |
-        echo "Deregistering repository runner: $RUNNER_ID ..."
+        # Offline runners are automatically deleted after 30 days, so we only emit a warning for runner deregistration failure
+        if [ -z "$RUNNER_ID" ]; then
+            echo "WARN: Unable to deregister GitHub repository runner (runner ID not available)
+        else
+            echo "Deregistering GitHub repository runner: $RUNNER_ID ..."
+            gh api -X DELETE -H 'Accept: application/vnd.github.v3+json' \
+              "repos/$GITHUB_REPO/actions/runners/$RUNNER_ID" || echo "WARN: Failed to deregister GitHub repository runner (GitHub API call failed)"
+        fi
         
-        gh api -X DELETE -H 'Accept: application/vnd.github.v3+json' \
-          "repos/$GITHUB_REPO/actions/runners/$RUNNER_ID" || echo "WARN: Failed to deregister runner"
-        
-        echo "Terminating EC2 instance: $INSTANCE_ID ..."
-        
-        aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" > /dev/null
-        
-        echo "Repository runner stopped"
+        # Failure to terminate the EC2 instance will incur unnecessary costs, so we fail loudly to ensure the user notices it
+        if [ -z "$INSTANCE_ID" ]; then
+            echo "ERROR: Unable to terminate EC2 instance (instance ID not available)
+            exit 1
+        else
+            echo "Terminating EC2 instance: $INSTANCE_ID ..."
+            aws ec2 terminate-instances --instance-ids "$INSTANCE_ID" > /dev/null
+        fi
       env:
         GH_TOKEN: ${{ inputs.github-token }}
         AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
