Update action.yml

diff --git a/stop/action.yml b/stop/action.yml
--- a/stop/action.yml
+++ b/stop/action.yml
@@ -26,7 +26,7 @@ runs:
       
         echo "Deregistering repository runner: $runner_id ..."
         
-        gh api -X DELETE -H "Accept: application/vnd.github.v3+json" repos/${{ github.repository }}/actions/runners/$runner_id
+        gh api -X DELETE -H "Accept: application/vnd.github.v3+json" repos/${{ github.repository }}/actions/runners/$runner_id || echo "Failed to deregister runner"
         
         echo "Terminating EC2 instance: $instance_id ..."
         
